### ISSUE TITLE
Prepare base VM for VirtualBox

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/iugw2017#1]

**Comment by jgarcial** [comment]
Hi,
I saw the VMs and the  [Readme](https://github.com/inveniosoftware/iugw2017/blob/master/0-prerequisites/README.md) file earlier today. I am having issues setting them up. Are they ready yet?

If so, this is what I noticed:
1. The 4 vboxnet do not show in the "Host-only Networks" tab.
2. The log and the shared folders are under \Users\lnielsen. Is this ok? I tried to edit the shared folder path but VirtualBox won't let me.

**Comment by tiborsimko** [comment]
@jgarcial You can try these boxes:

- https://simko.web.cern.ch/simko/tmp/iugw2017/README.rst

but they are running an "older" Invenio 3 demo site instance.  

We are still updating things regarding VMs... the best is to simply wait a day or two...

**Comment by lnielsen** [comment]
@jgarcial They probably won't be ready until Tuesday ;-) We'll be providing USB sticks with everything on :-)
